export const commands = [
    { cmd: "about", description: "learn about me", spaces: 13 },
    // { cmd: "blog", description: "read my blog", spaces: 0 },
    { cmd: "certifications", description: "view earned certifications", spaces: 4 },
    { cmd: "clear", description: "clear the terminal", spaces: 13 },
    { cmd: "education", description: "view education history", spaces: 9 },
    { cmd: "email", description: "send me an email", spaces: 13 },
    { cmd: "experience", description: "view work experience", spaces: 8 },
    { cmd: "github", description: "check out my code", spaces: 12 },
    { cmd: "help", description: "list available commands", spaces: 14 },
    { cmd: "hello", description: "display welcome message", spaces: 13 },
    { cmd: "linkedin", description: "visit my LinkedIn", spaces: 10 },
    { cmd: "portfolio", description: "browse portfolio projects", spaces: 9 },
    { cmd: "resume", description: "download my resume", spaces: 12 },
    { cmd: "themes", description: "change terminal theme", spaces: 12 },
    { cmd: "tools", description: "see my development tools", spaces: 13 },
    { cmd: "quote", description: "view a favorite quotes", spaces: 13 },
];
