name: Test and Lint

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lint

      - name: Run tests
        run: yarn test
